language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1
  - nightly

notifications:
  email: false

script:
  - julia --project --check-bounds=yes -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
    
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage");'
  - julia --project -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl
  